version: '3.8'

services:
  agent:
    build: .
    container_name: monadgotchi-agent
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONAD_RPC_URL=${MONAD_RPC_URL}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - AGENT_PRIVATE_KEY=${AGENT_PRIVATE_KEY}
      - ENVIO_ENDPOINT=${ENVIO_ENDPOINT}
      - POLL_INTERVAL_MS=${POLL_INTERVAL_MS:-60000}
      - MIN_HUNGER_THRESHOLD=${MIN_HUNGER_THRESHOLD:-90}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - MAX_CONCURRENT_FEEDS=${MAX_CONCURRENT_FEEDS:-5}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - HEALTH_CHECK_PORT=${HEALTH_CHECK_PORT:-3000}
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
