# Envio HyperIndex Configuration
name: monadgotchi-indexer
description: Monadgotchi virtual pet indexer

networks:
  - id: 10143
    start_block: 44404850
    rpc_url: https://testnet-rpc.monad.xyz

contracts:
  - name: Monadgotchi
    address: 0x750E675Fb7f1fBDe1944889AE12d311e3ae7E06b
    abi_file_path: abis/Monadgotchi.json
    handler: src/EventHandlers.ts
    events:
      - event: PetMinted
      - event: PetHungerUpdated  
      - event: PetFainted
      - event: PetFed